/** ~100 خطاً شائعاً (عربي / متعدد النصوص) من Google Fonts — التحميل عند الاختيار */
export interface GoogleArabicFontEntry {
  key: string;
  label: string;
  googleFamily: string;
}

function entry(key: string, label: string, googleFamily: string): GoogleArabicFontEntry {
  return { key, label, googleFamily };
}

export const GOOGLE_ARABIC_FONT_CATALOG: GoogleArabicFontEntry[] = [
  entry("tajawal", "تجوال · Tajawal", "Tajawal"),
  entry("cairo", "القاهرة · Cairo", "Cairo"),
  entry("gulzar", "جلزار · Gulzar", "Gulzar"),
  entry("almarai", "المرعى · Almarai", "Almarai"),
  entry("amiri", "أميري · Amiri", "Amiri"),
  entry("noto-naskh-arabic", "نوتو نسخ · Noto Naskh Arabic", "Noto Naskh Arabic"),
  entry("noto-kufi-arabic", "نوتو كوفي · Noto Kufi Arabic", "Noto Kufi Arabic"),
  entry("noto-sans-arabic", "نوتو سانس · Noto Sans Arabic", "Noto Sans Arabic"),
  entry("changa", "تشانغا · Changa", "Changa"),
  entry("el-messiri", "المسيري · El Messiri", "El Messiri"),
  entry("katibeh", "كتبة · Katibeh", "Katibeh"),
  entry("lalezar", "لالزار · Lalezar", "Lalezar"),
  entry("lateef", "لطيف · Lateef", "Lateef"),
  entry("mirza", "ميرزا · Mirza", "Mirza"),
  entry("scheherazade-new", "شهرزاد · Scheherazade New", "Scheherazade New"),
  entry("scheherazade", "شهرزاد · Scheherazade", "Scheherazade"),
  entry("reem-kufi", "ريم كوفي · Reem Kufi", "Reem Kufi"),
  entry("reem-kufi-fun", "ريم كوفي فن · Reem Kufi Fun", "Reem Kufi Fun"),
  entry("reem-kufi-ink", "ريم كوفي حبر · Reem Kufi Ink", "Reem Kufi Ink"),
  entry("mada", "مدى · Mada", "Mada"),
  entry("kufam", "كوفام · Kufam", "Kufam"),
  entry("harmattan", "هرمتان · Harmattan", "Harmattan"),
  entry("markazi-text", "مركزي · Markazi Text", "Markazi Text"),
  entry("lemonada", "ليمونادة · Lemonada", "Lemonada"),
  entry("alexandria", "الإسكندرية · Alexandria", "Alexandria"),
  entry("beiruti", "بيروتي · Beiruti", "Beiruti"),
  entry("playpen-sans-arabic", "Playpen Sans Arabic", "Playpen Sans Arabic"),
  entry("baloo-bhaijaan-2", "بالو بهيجان · Baloo Bhaijaan 2", "Baloo Bhaijaan 2"),
  entry("ibm-plex-sans-arabic", "IBM Plex Sans Arabic", "IBM Plex Sans Arabic"),
  entry("vibes", "فايبز · Vibes", "Vibes"),
  entry("qahiri", "قاهري · Qahiri", "Qahiri"),
  entry("rakkas", "رقّاص · Rakkas", "Rakkas"),
  entry("aref-ruqaa", "عارف رقعة · Aref Ruqaa", "Aref Ruqaa"),
  entry("aref-ruqaa-ink", "عارف رقعة حبر · Aref Ruqaa Ink", "Aref Ruqaa Ink"),
  entry("rubik", "روبيك · Rubik", "Rubik"),
  entry("amiri-quran", "أميري قرآن · Amiri Quran", "Amiri Quran"),
  entry("jomhuria", "جمهورية · Jomhuria", "Jomhuria"),
  entry("marhey", "مرحي · Marhey", "Marhey"),
  entry("magenda", "ماجندا · Magenda", "Magenda"),
  entry("comforter", "كمفورتر · Comforter", "Comforter"),
  entry("comforter-brush", "Comforter Brush", "Comforter Brush"),
  entry("hurricane", "هوريكان · Hurricane", "Hurricane"),
  entry("oldenburg", "أولدنبورغ · Oldenburg", "Oldenburg"),
  entry("cairo-play", "Cairo Play", "Cairo Play"),
  entry("handjet", "Handjet", "Handjet"),
  entry("bonbon", "Bonbon", "Bonbon"),
  entry("blaka", "Blaka", "Blaka"),
  entry("blaka-hollow", "Blaka Hollow", "Blaka Hollow"),
  entry("blaka-ink", "Blaka Ink", "Blaka Ink"),
  entry("festive", "Festive", "Festive"),
  entry("roboto", "Roboto", "Roboto"),
  entry("open-sans", "Open Sans", "Open Sans"),
  entry("lato", "Lato", "Lato"),
  entry("montserrat", "Montserrat", "Montserrat"),
  entry("poppins", "Poppins", "Poppins"),
  entry("nunito", "Nunito", "Nunito"),
  entry("mulish", "Mulish", "Mulish"),
  entry("work-sans", "Work Sans", "Work Sans"),
  entry("ubuntu", "Ubuntu", "Ubuntu"),
  entry("source-sans-3", "Source Sans 3", "Source Sans 3"),
  entry("dm-sans", "DM Sans", "DM Sans"),
  entry("figtree", "Figtree", "Figtree"),
  entry("outfit", "Outfit", "Outfit"),
  entry("sora", "Sora", "Sora"),
  entry("manrope", "Manrope", "Manrope"),
  entry("plus-jakarta-sans", "Plus Jakarta Sans", "Plus Jakarta Sans"),
  entry("space-grotesk", "Space Grotesk", "Space Grotesk"),
  entry("readex-pro", "Readex Pro", "Readex Pro"),
  entry("lexend", "Lexend", "Lexend"),
  entry("lexend-deca", "Lexend Deca", "Lexend Deca"),
  entry("lexend-exa", "Lexend Exa", "Lexend Exa"),
  entry("lexend-mega", "Lexend Mega", "Lexend Mega"),
  entry("lexend-tera", "Lexend Tera", "Lexend Tera"),
  entry("red-hat-display", "Red Hat Display", "Red Hat Display"),
  entry("red-hat-text", "Red Hat Text", "Red Hat Text"),
  entry("rubik-bubbles", "Rubik Bubbles", "Rubik Bubbles"),
  entry("rubik-moonrocks", "Rubik Moonrocks", "Rubik Moonrocks"),
  entry("rubik-pixels", "Rubik Pixels", "Rubik Pixels"),
  entry("rubik-spray-paint", "Rubik Spray Paint", "Rubik Spray Paint"),
  entry("rubik-microbe", "Rubik Microbe", "Rubik Microbe"),
  entry("rubik-beastly", "Rubik Beastly", "Rubik Beastly"),
  entry("rubik-distressed", "Rubik Distressed", "Rubik Distressed"),
  entry("rubik-broken-fax", "Rubik Broken Fax", "Rubik Broken Fax"),
  entry("rubik-maps", "Rubik Maps", "Rubik Maps"),
  entry("rubik-gemstones", "Rubik Gemstones", "Rubik Gemstones"),
  entry("rubik-lines", "Rubik Lines", "Rubik Lines"),
  entry("rubik-dirt", "Rubik Dirt", "Rubik Dirt"),
  entry("rubik-puddles", "Rubik Puddles", "Rubik Puddles"),
  entry("rubik-scribble", "Rubik Scribble", "Rubik Scribble"),
  entry("rubik-storm", "Rubik Storm", "Rubik Storm"),
  entry("rubik-vinyl", "Rubik Vinyl", "Rubik Vinyl"),
  entry("rubik-wet-paint", "Rubik Wet Paint", "Rubik Wet Paint"),
  entry("rubik-marker-hatch", "Rubik Marker Hatch", "Rubik Marker Hatch"),
  entry("rubik-maze", "Rubik Maze", "Rubik Maze"),
  entry("rubik-iso", "Rubik Iso", "Rubik Iso"),
  entry("rubik-glitch", "Rubik Glitch", "Rubik Glitch"),
  entry("rubik-80s-fade", "Rubik 80s Fade", "Rubik 80s Fade"),
  entry("rubik-one", "Rubik One", "Rubik One"),
  entry("lexend-giga", "Lexend Giga", "Lexend Giga"),
  entry("lexend-zetta", "Lexend Zetta", "Lexend Zetta"),
];
